spring.application.name=prajaconnect

spring.datasource.url=jdbc:mysql://localhost:3306/prajaconnect_db
spring.datasource.username=root
spring.datasource.password=Akhila_11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# JWT Configuration
prajaconnect.app.jwtSecret=PrajaConnectSecretKeyForJwtAuthenticationWhichShouldBeLongEnoughToWorkWithHS256AlgorithmAndThenSomeMore
prajaconnect.app.jwtExpirationMs=86400000

# File Upload Configuration
file.upload-dir=uploads
